name: my_fyp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # App main dependencies
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.4
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  fluttertoast: ^8.2.8
  youtube_player_flutter: ^9.1.1
  permission_handler: ^11.3.1
  flutter_downloader: ^1.11.8
  flutter_gemini: ^3.0.0
  cached_network_image: ^3.4.1
  video_player: ^2.5.3
  google_generative_ai:
  intl:
  syncfusion_flutter_pdfviewer:
  # I added latest safe version for you
  # (Optional downgrade to remove desktop warnings)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
